using System;

namespace Lucky_Numbers
{
    class Program
    {
        static void Main(string[] args)
        {
            //declare global variables

            int startNum = 0;
            int endNum = 0;
            int luckyNumOne = 0;
            int luckyNumTwo = 0;
            int luckyNumThree = 0;
            int luckyNumFour = 0;
            int luckyNumFive = 0;
            int luckyNumSix = 0;
            bool validNum;
            string displayLuckyNum = "Lucky Number: ";
            string jackPotAmt = "$50,000.00";
            int numCorrectGuess = 0;
            int userWon = 0;
            bool playAgain;
            int[] userNumbers = new int[6];
            int isValidNum = 0;
            int totalValidNums = 0;



            //Tell the user you're starting the game
            //and some simple directions


            Console.WriteLine("Ok, let's Play Lucky Numbers! The Jackpot is worth " + jackPotAmt);
            Console.WriteLine();
            Console.WriteLine("You will be asked to enter a starting and an ending number.");
            Console.WriteLine();
            Console.WriteLine("Obviously the starting number must be lower than the ending number!");
            Console.WriteLine();


            //ask the user for a starting number and ending number


            Console.WriteLine("Please enter a starting number.");
            startNum = int.Parse(Console.ReadLine());
            Console.WriteLine();
            Console.WriteLine("Please enter an ending number.");
            endNum = int.Parse(Console.ReadLine());
            Console.WriteLine();


            //Now we'll ask the user to input 6 numbers they think will match 
            //the lucky numbers automatically generated by the lottery.
            //each number entered is compared to the start and end number range to be sure they're valid;
            //if not, don't decrement i and get a new value until
            //there are 6 valid entries            
            //then populate an array with the numbers the user enters;




            for (int i = 0; i < userNumbers.Length; i++)
            {
                Console.WriteLine("Please enter a lucky number");
                userNumbers[i] = int.Parse(Console.ReadLine());
                isValidNum = userNumbers[i];
             //   Console.WriteLine(userNumbers[i]);
                if ((isValidNum < startNum) || (isValidNum >= endNum))
                {
                    Console.WriteLine("The number you chose is not within your range.");
                    Console.WriteLine("Please pick a lucky number greater than " + startNum + "and less than " + endNum);
                    i--;

                }
                else
                {
                    Console.WriteLine();
                    //   Console.WriteLine(isValidNum == userNumbers[i]);

                }

            }



            //first we'll instantiate & initialize a new random object
            //now we'll populate the random numbers array
            //with the random number generator
            //and use startNum and endNum to set the range
            //of numbers to be generated

            Random r = new Random();
            int[] randomNumbers = new int[6];

            for (int i = 0; i < randomNumbers.Length; i++)
            {
                randomNumbers[i] = r.Next(startNum, endNum);
                Console.WriteLine(randomNumbers[i]);
            }


            //Now we need to check and see how many matches the user
            //had with the randomly generated numbers

            for (int i = 0; i < userNumbers.Length; i++)
            {
                if (userNumbers[i] == randomNumbers[0])
                {
                    Console.WriteLine("this value is a match" + randomNumbers[0]);
                }

                else if (userNumbers[i] == randomNumbers[1])
                {
                    Console.WriteLine("this value is a match" + randomNumbers[1]);
                }

                else if (userNumbers[i] == randomNumbers[2])
                {
                    Console.WriteLine("this value is a match" + randomNumbers[2]);
                }

                else if (userNumbers[i] == randomNumbers[3])
                {
                    Console.WriteLine("this value is a match" + randomNumbers[3]);
                }

                else if (userNumbers[i] == randomNumbers[4])
                {
                    Console.WriteLine("this value is a match" + randomNumbers[4]);
                }
                else if (userNumbers[i] == randomNumbers[5])
                {
                    Console.WriteLine("this value is a match" + randomNumbers[5]);
                }
                    //else if (userNumbers[i] == randomNumbers[])
                    //{
                    //    Console.WriteLine("the values are equal");
                    //    Console.WriteLine(randomNumbers[i] + userNumbers[i]);
                    //}
                    //   else Console.WriteLine("I'm sorry, you didn't match any lucky numbers.");

                }

        }
    }
}
