using System;

namespace Lucky_Numbers
{
    class Program
    {
        static void Main(string[] args)
        {
            //declare global variables
            
            int startNum = 0;
            int endNum = 0;
            int luckyNumOne = 0;
            int luckyNumTwo = 0;
            int luckyNumThree = 0;
            int luckyNumFour = 0;
            int luckyNumFive = 0;
            int luckyNumSix = 0;
            bool validNum;
            string displayLuckyNum = "Lucky Number: ";
            string jackPotAmt = "$50,000.00";
            int numCorrectGuess = 0;
            int userWon = 0;
            bool playAgain;
            int[] userNumbers = new int[6];
            


            //Tell the user you're starting the game
            //and some simple directions


            Console.WriteLine("Ok, let's Play Lucky Numbers!");
            Console.WriteLine();
            Console.WriteLine("You will be asked to enter a starting and an ending number.");
            Console.WriteLine();
            Console.WriteLine("Obviously the starting number must be lower than the ending number!");
            Console.WriteLine();


            //ask the user for a starting number and ending number
            

            Console.WriteLine("Please enter a starting number.");
            startNum = int.Parse(Console.ReadLine());
            Console.WriteLine();
            Console.WriteLine("Please enter an ending number.");
            endNum = int.Parse(Console.ReadLine());
            Console.WriteLine();

            //create an array with a length of two
            //assign startNum and endNum to the array

            //int[] numRange = new int[2];

            //ask the user to input 6 numbers they think will match 
            //the lucky numbers automatically generated by the lottery
            //that fall within the number range they have specified
            //populate an array with the numbers the user enters;

            

            for (int i = 0; i < userNumbers.Length; i++)
            {
                Console.WriteLine("Please enter a lucky number" );
                userNumbers[i] = int.Parse(Console.ReadLine());
              //  Console.WriteLine("You picked lucky number " + userNumbers[i]);//test the numbers are in the array
            }

            //first we'll instantiate & initialize a new random object
            //now we'll populate the random numbers array
            //with the random number generator
            //and use startNum and endNum to set the range
            //of numbers to be generated

            Random r = new Random();
            int[] randomNumbers = new int[6];

            for (int i = 0; i < randomNumbers.Length; i++)
            {
                randomNumbers[i] = r.Next(startNum, endNum);
                Console.WriteLine(randomNumbers[i]);
            }

        }
    }
}
